config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'prueba', to: 'pages#prueba'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :review_places, only: :create
  end

  resources :publications do
    get :increase_counter
  end

  resources :review_publications, only: :destroy

  resources :review_places, only: :destroy
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-lg-start bg-dark text-white">
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <div class="me-5 d-none d-lg-block">
      <span>Conectate con nosotros a través de nuestras redes:</span>
    </div>
    <div>
      <a href="https://twitter.com/Srgndrscruz" class="me-4 text-footer">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://www.facebook.com/sergio.rcruz.18" class="me-4 text-footer">
        <i class="fab fa-facebook"></i>
      </a>
      <a href="https://www.instagram.com/TurismTAG/" class="me-4 text-footer">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="https://www.linkedin.com/in/sergio-rodas-cruz-405762235/" class="me-4 text-footer">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="https://github.com/sergioski9" class="me-4 text-footer">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </section>
  <section class="">
    <div class="container text-center text-md-start ">
      <div class="row mt-3">
        <div class="col-6 col-sm-6 col-md-3 col-lg-4 col-xl-3 mx-auto mt-5">
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>TourBol
          </h6>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-2 col-xl-2 mx-auto">
          <h6 class="text-uppercase fw-bold mb-4">
            Links útiles
          </h6>
          <p>
            <a href="#!" class="text-footer">Sobre nosotros</a>
          </p>
          <p>
            <a href="#!" class="text-footer">Nuestros Lugares</a>
          </p>
          <p>
            <a href="#!" class="text-footer">Activar Premium</a>
          </p>
        </div>
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0">
          <h6 class="text-uppercase fw-bold mb-4">
            Contáctanos
          </h6>
          <p><i class="fas fa-home me-3"></i> Santa Cruz, Bolivia</p>
          <p><i class="fas fa-envelope me-3"></i>tourbol@turism.bol</p>
          <p><i class="fas fa-phone me-3"></i> + 591 691 528 11</p>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h4 class="mt-1">TourBol</h4>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_tag places_path, class: "d-flex mx-3", method: :get do %>
      <div class="input-group">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Buscar Lugares"
      %>
       <button type="submit" class="btn btn-light"><i class="fas fa-search"></i></button>
      </div>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Inicio", root_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Destinos", places_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publicaciones", publications_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= image_tag "#{cl_image_path current_user.photo.key}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dgzbf6kp2/image/upload/c_scale,h_200,w_200/v1652472231/development/ivoevb9zgmyu06e2bxa6zwf45kqt.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Inicio", root_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Lugares", places_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publicaciones", publications_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Iniciar Sesion", new_user_session_path, class: "nav-link", style: "color: white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>