config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'prueba', to: 'pages#prueba'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :review_places, only: :create
  end

  resources :publications do
    get :increase_counter
  end

  resources :review_publications, only: :destroy

  resources :review_places, only: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :publications, dependent: :destroy
  has_many :review_places, dependent: :destroy

  has_many_attached :photos, dependent: :destroy

  validates :name, :description, :rating, presence: true
  validates :city, :recomendation, :other_recomendation, presence: true
  validates :how_to_get, :what_to_bring, presence: true

  def top_3
    if publications.count <= 3
      publications
    else
      publications.order("user_id").reverse.take(3)
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_place, only: [ :show, :edit, :update, :destroy ]

  def index
    @places = Place.all
    @city = Place.where(city: params[:city]) if params[:city].present?
    sql_query = " \
        places.name @@ :query \
        OR places.description @@ :query \
        OR places.city @@ :query
      "
    @places = Place.where(sql_query, query: "%#{params[:query]}%") if params[:query].present?
  end

  def show
    @publications_top = @place.top_3
    @review = ReviewPlace.new(place: @place)
    @markers = @place.publications.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window: render_to_string(partial: 'info_window', locals: { place: place })
      }
    end
  end

  def new
    @place = Place.new
    @cities = ["Santa Cruz de la Sierra", "Potosí", "Oruro", "Pando", "Beni", "Tarija", "Sucre", "La Paz", "Cochabamba"]
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def edit
    @cities = ["Santa Cruz de la Sierra", "Potosí", "Oruro", "Pando", "Beni", "Tarija", "Sucre", "La Paz", "Cochabamba"]
  end

  def update
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    @place.destroy

    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :city, :recomendation, :how_to_get, :what_to_bring, :other_recomendation, :rating, photos: [])
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/views/places/_info_window.html.erb
<h1>Hello from pop up</h1>

app/views/places/edit.html.erb
<div class="container py-5 my-5">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3 class="text-shadow">Edit Place, Just Admin!</h3>
        <%= simple_form_for @place do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :rating %>
          <%= f.input :city, as: :select, collection: @cities %>
          <%= f.input :recomendation %>
          <%= f.input :other_recomendation %>
          <%= f.input :what_to_bring %>
          <%= f.input :how_to_get %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: "btn btn-outline-dark rounded-pill px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<article id="index the place">
  <section>
    <div class="container text-center text-shadow my-5">
      <h2><strong>¡Escoge el Lugar que más te guste! </strong></h2>
      <p><small><em class="text-muted">¡Presiona la imagen para ver toda su informacion!</em></small></p>
    </div>
    <div class="container-fluid my-5">
      <div class="row justify-content-center">
        <% if params[:city].present? %>
          <% @city.each do |place| %>
            <div class="text-none col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4" data-aos="fade-up" data-aos-duration="2000">
              <%= link_to place_path(place) do %>
                <div class="box-shadow card-places my-4">
                  <div class="card-category-place" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= cl_image_path place.photos.first.key %>')">
                    <div>
                      <% place.rating.to_i.times do %>
                        <i class="fas fa-star star-yellow"></i>
                      <% end %>
                      <h3 class="text-shadow"><strong><%= place.name.first(20) %>...</strong></h3>
                      <h5 class="text-shadow"><strong><%= place.city %></strong></h5>
                      <p><%= place.description.first(90) %>...</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <% @places.each do |place| %>
            <div class="text-none col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4" data-aos="fade-up" data-aos-duration="2000">
              <%= link_to place_path(place) do %>
                <div class="box-shadow card-places my-4">
                  <div class="card-category-place" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= cl_image_path place.photos.first.key %>')">
                    <div class="text-shadow">
                      <div class="color-white">
                        <h3 class=""><strong><%= place.name.first(20) %>...</strong></h3>
                        <% place.rating.to_i.times do %>
                          <i class="fas fa-star star-yellow"></i>
                        <% end %>
                      </div>
                      <h5 class="text-shadow"><strong><%= place.city %></strong></h5>
                      <p><%= place.description.first(90) %>...</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</article>

app/views/places/new.html.erb
<div class="container py-5 my-5">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3 class="text-shadow">Add Place, Just Admin!</h3>
        <%= simple_form_for @place do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :rating %>
          <%= f.input :city, as: :select, collection: @cities %>
          <%= f.input :recomendation %>
          <%= f.input :other_recomendation %>
          <%= f.input :what_to_bring %>
          <%= f.input :how_to_get %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: "btn btn-outline-dark rounded-pill px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<article>
  <section>
    <div id="carouselExampleFade" class="carousel slide carousel-fade text-shadow" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="7000">
          <div class="banner-place text-center text-shadow" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= cl_image_path @place.photos&.first&.key %>);">
          </div>
        </div>
        <div class="carousel-item" data-bs-interval="7000">
          <div class="banner-place text-center text-shadow" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= cl_image_path @place.photos&.second&.key %>);">
          </div>
        </div>
        <div class="carousel-item text-center" data-bs-interval="7000">
          <div class="banner-place text-center text-shadow" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= cl_image_path @place.photos&.last&.key %>);">
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 my-4">
          <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 border-end p-3 my-3">
              <h3 class="text-center mb-4 text-shadow">
                <strong><%= @place.name %> - <%= @place.city %></strong>
              </h3>
              <p class="mt-3 text-justify"><%= @place.description %></p>
              <div class="text-center p-4">
                <% @place.rating.to_i.times do %>
                  <i class="fas fa-star star-yellow"></i>
                <% end %>
                <h4 class="d-inline-block mx-4 text-shadow">
                  <strong>Estrellas del Destino</strong>
                </h4>
                <p>
                  <small>
                    <em class="text-muted">
                      creado <%= distance_of_time_in_words_to_now(@place.created_at) %> aprox.
                    </em>
                  </small>
                </p>
              </div>
              <div class="container p-4 text-center">
                <h4><strong>¡Crea una Publicacion para este Lugar!</strong></h4>
                <p><small class="text-muted">Crea una publicacion ya sea para compartir tus experiencias con este Lugar, o Compartir un negocio, restaurante, hotel, etc.</small></p>
                <p><small>¡Para que tu negocio sea visible para todos los turistas!</small></p>
                <%= link_to "Crear Publicacion", new_publication_path, class: "btn btn-outline-dark rounded-pill px-4" %>
              </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 border-start p-3 my-3">
              <h3 class="text-center text-shadow">
                <strong>Información Acerca del Lugar</strong>
              </h3>
              <div class="row justify-content-between p-4">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                  <div class="card-place-show-information my-3">
                    <img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1653512120/development/caminar-place_r3yfwl.png" alt="ilustracion caminando">
                  </div>
                  <h5 class="text-center"><strong>Como Llegar?</strong></h5>
                  <p class="text-justify"><%= @place.how_to_get %></p>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                  <div class="card-place-show-information my-3">
                    <img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1653512413/development/llevar-place_dfnsfu.png" alt="ilustracion-mochla">
                  </div>
                  <h5 class="text-center"><strong>Que Llevar?</strong></h5>
                  <p class="text-justify"><%= @place.what_to_bring %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <div class="row justify-content-center">
            <div id="reviews" class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-5 px-4">
              <h3 class="text-shadow">Reviews</h3>
              <% if @place.review_places.empty? %>
                <small><em class="text-muted">¡Sé el primero en dejar una review de este lugar!</em></small>
              <% end %>
              <% @place.review_places.last(3).each do |review| %>
                <div>
                  <% review.rating.times do %>
                    <i class="fas fa-star star-yellow"></i>
                  <% end %>
                  <small><em class="text-muted">creado <%= distance_of_time_in_words_to_now(review.created_at) %> aprox.</em></small>
                  <p id="review-<%= review.id %>" class="mb-0 text-shadow"><%= review.comment %></p>
                </div>
                <hr>
              <% end %>
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-5">
              <div class="bg-white rounded p-3">
                <h5 class="text-shadow">Agrega tu review</h5>
                <%= simple_form_for([@place, @review], remote: true) do |f| %>
                  <%= f.input :comment, placeholder: "Add your review here...", class: "text-shadow" %>
                  <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating",  class: "text-shadow", input_html: { data: { controller: "jquery-bar-rating" } } %>
                  <%= f.submit class:"btn btn-outline-dark px-4 rounded-pill" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</article>
<article>
  <section>
    <h3 class="text-center text-shadow my-5"><strong>¡Top 3 Publicaciones, con las que los usuarios mas se han Contactado!</strong></h3>
    <div class="container row justify-content-center">
      <% @publications_top.each do |publication| %>
        <div class="my-4 mx-4 box-shadow bg-white col-11 col-sm-11 col-md-5 col-lg-5 col-xl-4 card-publications" data-aos="fade-up" data-aos-duration="2000">
          <div class="d-flex mr-2 my-2">
            <div class="avatar-publications mx-2" style="background-image: url(<%= publication.user.photo.attached? ? cl_image_path(publication.user.photo.key) : 'https://res.cloudinary.com/dgzbf6kp2/image/upload/c_scale,h_1536,w_1920/v1652472231/development/ivoevb9zgmyu06e2bxa6zwf45kqt.jpg' %>)"></div>
            <div class="container-header-publications">
              <h6><%= publication.user.first_name %></h6>
              <p><small class="text-muted"><%= publication.place.name %></small></p>
            </div>
          </div>
          <div class="container-photo-publications">
            <img src="<%= cl_image_path publication.photos&.first&.key %>" alt="foto-de-publicacion">
          </div>
          <div class="my-3 container-letters-publications">
            <p><%= publication.title.first(30) ... %></p>
            <p><%= publication.description.first(30) %> ...</p>
            <div class="border-top border-bottom">
              <div class="margin-auto text-center rounded-pill my-3 tags-publications">
                <p>personas que se han contactado: <b><%= publication.counter %></b></p>
              </div>
            </div>
            <p class="p-1 text-center"><small><em class="text-muted">Created <%=  distance_of_time_in_words_to_now(publication.created_at) %></em></small></p>
            <div class="text-center">
              <%= link_to "Ver Publicacion", publication_path(publication), class: "mt-3 btn btn-outline-dark rounded-pill px-4" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="text-center my-5">
      <h3><strong>¡Ubicación del lugar y de todas las publicaciones dentro del Destino!</strong></h3>
    </div>

    <div style="width: 100%; height: 500px;"
      data-controller="mapbox"
      data-mapbox-target="container"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="container-fluid my-5">
      <h4 class="text-center mt-5 text-shadow"><strong>Ver todas las Publicaciones</strong></h4>
      <div class="text-center">
        <%= link_to "Ver Publicaciones", publications_path, class: "px-4 btn btn-outline-dark rounded-pill" %>
      </div>
    </div>
  </section>
</article>
<section>
  <div class="border-top col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 border-bottom">
    <div class="container-fluid">
      <div class="row text-center my-5">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-md-8 col-lg-7 col-xl-6">
              <h3 class="my-4">
                <strong>Recomendaciones</strong>
              </h3>
              <div class="card-place-show-recomendation">
                <img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1653513660/development/recomendaciones_jrfzwk.png" alt="ilustracion recomendacion">
              </div>
            </div>
          </div>
        </div>
        <div class="border-end col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 my-3">
          <h5 class="my-3"><strong>Principal</strong></h5>
          <p><%= @place.recomendation %></p>
        </div>
        <div class="border-start col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 my-3">
          <h5 class="my-3"><strong>Secundaria</strong></h5>
          <p><%= @place.other_recomendation %></p>
        </div>
      </div>
    </div>
  </div>
</section>